const sendResponse = require("../utils/sendResponse");
const sendDeletableResponse = require("../utils/sendDeletableResponse");

module.exports = message => {
    let request = message.content.substr(message.content.indexOf(" "));
    if (request === "") {
        return sendDeletableResponse(message, `You... didn't ask me to translate anything.`);
    }

    let translatedRequest = request.toLowerCase();
    for (let [key, value] of translations) {
        translatedRequest.replace(key, value);
    }

    if (request.toUpperCase() == request) {
        translatedRequest.toUpperCase();
    }

    sendResponse(message, `I think that's something like, "${translatedRequest}"`);
};

// Maps iterate in insertion order
const translations = new Map([
    ["tanyao", "All Simples"],
    ["kuitan", "open tanyao"],
    ["tenpai", "ready"],
    ["tsumogiri", "drawn tile cut"],
    ["tsumo", "self-draw"],
    ["tedashi", "cut from hand"],
    ["ryanmen", "side wait"],
    ["kanchan", "closed wait"],
    ["penchan", "edge wait"],
    ["shanpon", "double pon wait"],
    ["tanki", "pair wait"],
    ["hadaka", "four-call"],
    ["entotsu", "side wait plus pon wait"],
    ["sanmenchan", "3-way side wait"],
    ["gyakuten", "comeback"],
    ["nakasuji", "middle suji"],
    ["nagare", "flow"],
    ["shanten", "away from ready"],
    ["ukeire", "effective tiles"],
    ["iishanten", "1-away"],
    ["ryanshanten", "2-away"],
    ["nobetan", "stretched single"],
    ["yonrenkei", "four consecutive tiles"],
    ["nakabukure", "bulging shape"],
    ["menzen", "closed"],
    ["sanshoku", "Mixed Triple Sequence"],
    ["iipeikou", "Pure Double Sequence"],
    ["dabuton", "double east"],
    ["chanta", "Half Outside Hand"],
    ["rinshan", "After a Kan"],
    ["chankan", "Robbing a Kan"],
    ["haitei", "final drawn tile"],
    ["houtei", "final discarded tile"],
    ["ryanpeikou", "Twice Pure Double Sequence"],
    ["chinitsu", "Full Flush"],
    ["nagashi", "Mangan At Draw"],
    ["chiitoitsu", "Seven Pairs"],
    ["sanshokudokou", "Triple Triplets"],
    ["sanankou", "Three Concealed Triplets"],
    ["sankantsu", "Three Quads"],
    ["toitoi", "All Triplets"],
    ["honitsu", "Half Flush"],
    ["shousangen", "Little Three Dragons"],
    ["honroutou", "All Terminals and Honors"],
    ["junchan", "Fully Outside Hand"],
    ["kokushi", "Thirteen Orphans"],
    ["chuuren", "Nine Gates"],
    ["tenhou", "Blessing of Heaven (or maybe the online platform)"],
    ["chihou", "Blessing of Earth"],
    ["renhou", "Blessing of Man"],
    ["suuankou", "Four Concealed Triplets"],
    ["suukantsu", "Four Quads"],
    ["ryuuiisou", "All Green"],
    ["chinroutou", "All Terminals"],
    ["tsuuiisou", "All Honors"],
    ["daisangen", "Big Three Dragons"],
    ["daisuushii", "Big Four Winds"],
    ["shousuushii", "Small Four Winds"],
    ["mawashi", "safely push"],
    ["betaori", "fully fold"],
    ["zentsu", "fully push"],
    ["noten", "not ready"],
    ["yamagoshi", "pass up a win to target another player"],
    ["tonpu", "East-only game"],
    ["hanchan", "East-South game"],
    ["sanma", "three player"],
    ["pao", "responsiblity for a yakuman"],
    ["sekinin barai", "responsibility for a yakuman"],
    ["chiitoi", "seven pairs"],
    ["tonpuu", "East-only game"],
    ["tonpuusen", "East-only game"],
    ["yama", "wall"],
    ["wanpai", "dead wall"],
    ["wanzu", "characters"],
    ["shichifukusei", "Seven Stars"],
    ["shabo", "dual pon wait"],
    ["harabote", "bulging shape"],
    ["bazoro", "rule adding 2 han to every won hand"],
    ["furikomi", "strategic deal-in"],
    ["sokurii", "instant riichi"],
    ["suufon renda", "Four Winds Draw"],
    ["suucha riichi", "Four Riichi Draw"],
    ["minkan", "open kan"],
    ["daiminkan", "called kan"],
    ["shouminkan", "added kan"],
    ["kuikae", "swap calling"],
    ["houou", "Phoenix room"],
    ["tokujou", "Upper Dan room"],
    ["joukyuu", "Lower Dan room"],
    ["ippan", "Beginner room"],
    ["agari", "win"],
    ["rentai", "1st + 2nd place rate"],
    ["tobi", "bankrupt"],
    ["keishiki", "tenpai without the ability to win"],
    ["keiten", "tenpai without the ability to win."],
    ["kabe", "walled tile"],
    ["genbutsu", "perfectly safe tile"],
    ["shimocha", "right player"],
    ["kamicha", "left player"],
    ["toimen", "player across"],
    ["ryankan", "double closed shape"],
    ["karagiri", "cut, from hand, the drawn tile"],
    ["damaten", "closed tenpai without riichi"],
    ["dama", "closed tenpai without riichi"],
    ["takame", "most valuable out"],
    ["yasume", "least valueable out"],
    ["sashikomi", "strategic deal-in"],
    ["ankan", "closed kan"],
    ["ryuukyoku", "exhaustive draw"],
    ["kyuushu", "9 tiles 9 types"],
    ["kskh", "9 tiles 9 types"],
    ["kyushu", "0 tiles 9 types"],
    ["aotenjou", "skyrocketing"],
    ["wareme", "hot wall rule"],
    ["manzu", "characters"],
    ["souzu", "bamboo"],
    ["pinzu", "circles"],
    ["honba", "repeat"],
    ["hms", "Hittori Mahjong Simulator"],
    ["mentsu", "complete shape"],
    ["taatsu", "incomplete shape"],
    ["toitsu", "pair."],
    ["koutsu", "triplet."],
    ["shuntsu", "run"],
    ["jantou", "final pair"],
    ["jansou", "mahjong parlour"],
    ["shuugi", "bonus payment"],
    ["kuisagari", "open penalty"],
    ["tenbo", "point sticks"],
    ["yakitori", "never won a hand"],
    ["washizu", "clear tiles"],
    ["kuinobashi", "shape-improving call"],
    ["sakigiri", "preemptive discard"],
    ["sotogawa", "an early discard making outer tiles safer"],
    ["oikake", "chasing"],
    ["zawa", "scary"],
    ["otoshi", "cut"],
    ["haipai", "starting hand"],
    ["daichisei", "Seven Stars"],
    ["ishinouenimosannen", "Three Years on the Stone"],
    ["renchan", "repeat"],
    ["paarenchan", "eight repeat yakuman"],
    ["sanrenkou", "Three Connected Triplets"],
    ["suurenkou", "Four Connected Triplets"],
    ["shiisanpuutaa", "13 Disconnected Tiles"],
    ["shiisuupuutaa", "14 Disconnected Tiles"],
    ["daisharin", "Big Wheels"],
    ["daichikurin", "Bamboo Forest"],
    ["daisuurin", "Numerous Numbers (look I didn't make the translation)"],
    ["karaten", "no-out tenpai"],
    ["machi", "wait"],
    ["atamahane", "head bump"],
    ["bakahon", "Half Flush only"],
    ["nomi", "only"],
    ["kita", "replaced North"],
    ["nuki", "replaced North"],
    ["meijin", "7d <2000R"],
    ["atozuke", "wait where only some outs give a yaku"],
    ["enchousen", "sudden death round"],
    ["oorasu", "All Last"],
    ["agariyame", "rule allowing dealer to end the game if they win during All Last in first"],
    ["moupai", "tilesface reading"],
    ["ganpai", "marked tiles"],
    ["musuji", "non-suji"],
    ["benikujaku", "Red Peacock"],
    ["bakaze", "round wind"],
    ["jikaze", "seat wind"],
    ["otakaze", "guest wind"],
    ["yonma", "four player."],
    ["shibori", "squeeze play"],
    ["ryanhan shibari", "two han restriction"],
    ["shibari", "restriction"],
    ["saburokyuu", "3-6-9 wait"],
    ["saburo", "3-6 wait"],
    ["kiriage", "counted"],
    ["kakan", "added kan"],
    ["ippatsu", "one-shot"],
    ["toitsuba", "round with many pairs"],
    ["paifu", "game record"],
    ["kyoutaku", "bonus sticks"],
    ["buttobi", "below zero points"],
    ["chombo", "greivous error"],
    ["sokuri", "instant riichi"],
    ["gari", "replaced tile"],
    ["natsuki", "the best bot ever"],
    ["sakizumo", "early drawing"],
    ["oyakaburi", "dealer's larger payment on tsumo"],
    ["shonpai", "live tile"],
    ["sanchahou", "Triple Ron Draw"],
    ["suukaikan", "Four Kan Draw"],
    ["ankou", "closed triplet"],
    ["anjun", "closed run"],
    ["minkou", "called triplet"],
    ["minjun", "called sequence"],
    ["jihai", "honor tiles"],
    ["yaochuu", "terminal and honor tiles"],
    ["aidayonken", "four tile gap"],
    ["ikasama", "cheating"],
    ["tengo", "1000 points to 50 yen."],
    ["tenpin", "1000 points to 100 yen."],
    ["dekapin", "1 point to 1 yen."],
    ["aka", "red"],
    ["oya", "dealer"],
    ["hatsu", "<:6z:466437922317402143>"],
    ["chun", "<:7z:466437922279784469>"],
    ["haku pocchi", "jewelled haku"],
    ["haku", "<:5z:466437921550106625>"],
    ["ton", "<:1z:466437921688518656>"],
    ["nan", "<:2z:466437922594226187>"],
    ["sha", "<:3z:466437922560671744>"],
    ["xia", "<:3z:466437922560671744>"],
    ["pei", "<:4z:466437922518728744>"],
    ["uma", "placement bonus"],
    ["oka", "ante"],
    ["itsu", "Pure Straight"],
    ["ittsu", "Pure Straight"],
    ["kawashite", "quickly winning to prevent opponents from winning"]
]);